language: node_js
node_js: lts/*
cache:
  npm: false
before_script: 
script:
- yarn install
- yarn build
deploy:
  local_dir: ".vuepress/dist/"
  provider: pages
  skip_cleanup: true
  name: Travis Build Bot
  keep_history: true
  on:
    branch: master
  target_branch: gh-pages
  github_token:
    secure: OZyZPP99jV9Vp4MlFCDBhteKi1TJDtNqwf2j8uaBkJfKiLlN27QH7PgW1jscarYvZ4OcRP1SVziwHxQr4Uyld+lQucM9kq24TwjHcUJjXxGNTGGQ+u7ggaTtlrONKU0BrmnZRgdJoncR2+OH7p/zyLD1G6bfIS+8ue67Py1lUGRKH21nrEUUlekYHPXLZMwSehOiFHnXbH47aDnEYO0BUMUCRsodp7fcr46n6uxX+huX5M4vfL1LFPmcNoyXV97wCaQDhnaJRXGg3fE8F91Bd9mT2ZTBxjPwEyGLOnzTtzoTMXS+Gl3SlCZhIsSWDVXmHOaA815s7T+InDzeP+6lblrZTg9JyhR9r+M7uHNxWm2rX6iHit0P+r8KslK3teLV9k1ByoD6YEj7z/jqsqz+JxTzo991QuhNWwsikkMrnFBkKw3xgccHeOOCOCPaEQuZOodbygnAVK64wJOM69o6DWjLWZUyuUyi9ym4hOxQyfGgQW76U9dgHsmvP1ZEfmlglNIljzlHS9L8Q0IQdBmk4gZDqrC0xRsVqORJjYMsD19o+Zi97XDLUtgh8+t9odU1oOh4QZYPpGom8ssIacKS9+sa+0PN1E2k2yz/wHbzrL1n3QU645sGmPuijjRd7dkjB7ahIdJQIJbZy7BlAqWtJQImq3ylYTUJGG6wPOoJOGM=
